import { existsSync, mkdirSync, readFileSync, rmdirSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { tool, type Plugin } from "@opencode-ai/plugin";

export interface MemoryEntry { id: string; type: "memory" | "decision"; tags: string[]; summary: string; createdAt: string; updatedAt: string; source: string; path: string; }
export interface MemoryIndex { version: 1; entries: MemoryEntry[]; }

const MEMORY_FILES = ["conventions.md", "context.md", "preferences.md"];
const slug = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 48) || "memory";
const memoryRoot = (directory: string) => join(directory, ".memory");
const indexPath = (directory: string) => join(memoryRoot(directory), "index.json");

export function ensureStore(directory: string): void {
  mkdirSync(join(memoryRoot(directory), "entries"), { recursive: true });
  mkdirSync(join(memoryRoot(directory), "decisions"), { recursive: true });
  for (const file of MEMORY_FILES) { const path = join(memoryRoot(directory), file); if (!existsSync(path)) writeFileSync(path, `# ${file.replace(".md", "")}\n`, "utf8"); }
  if (!existsSync(indexPath(directory))) writeFileSync(indexPath(directory), `${JSON.stringify({ version: 1, entries: [] }, null, 2)}\n`, "utf8");
}

export function loadIndex(directory: string): MemoryIndex {
  ensureStore(directory);
  const parsed: unknown = JSON.parse(readFileSync(indexPath(directory), "utf8"));
  if (!parsed || typeof parsed !== "object" || !Array.isArray((parsed as MemoryIndex).entries)) throw new Error("Invalid .memory/index.json");
  return parsed as MemoryIndex;
}

function saveIndex(directory: string, index: MemoryIndex): void { writeFileSync(indexPath(directory), `${JSON.stringify(index, null, 2)}\n`, "utf8"); }

const LOCK_TIMEOUT_MS = 5000;
const lockPath = (directory: string) => join(memoryRoot(directory), "index.lock");

function acquireLock(directory: string): void {
  const started = Date.now();
  while (true) {
    try { mkdirSync(lockPath(directory)); return; } catch { /* dir already exists, another process holds lock */ }
    if (Date.now() - started >= LOCK_TIMEOUT_MS) throw new Error("Timed out waiting for .memory/index.lock");
  }
}

function releaseLock(directory: string): void {
  try { rmdirSync(lockPath(directory)); } catch { /* already released, ignore */ }
}

export function addMemory(directory: string, text: string, tags: string[] = [], source = "cli"): MemoryEntry {
  ensureStore(directory);
  acquireLock(directory);
  try {
    const index = loadIndex(directory); const now = new Date().toISOString(); const normalized = text.trim();
    const duplicate = index.entries.find((entry) => entry.summary === normalized);
    if (duplicate) throw new Error(`Duplicate memory already exists: ${duplicate.id}`);
    const id = `${now.slice(0, 10).replaceAll("-", "")}-${String(index.entries.length + 1).padStart(4, "0")}-${slug(normalized)}`;
    const path = join("entries", `${id}.md`); const entry: MemoryEntry = { id, type: "memory", tags: [...new Set(tags.filter(Boolean))], summary: normalized, createdAt: now, updatedAt: now, source, path };
    writeFileSync(join(memoryRoot(directory), path), `---\nid: ${id}\ntype: memory\ntags: [${entry.tags.join(", ")}]\ncreated_at: ${now}\nupdated_at: ${now}\nsource: ${source}\n---\n\n${normalized}\n`, "utf8");
    index.entries.push(entry); saveIndex(directory, index); return entry;
  } finally {
    releaseLock(directory);
  }
}

export function searchMemory(directory: string, query: string): MemoryEntry[] {
  const terms = query.toLowerCase().split(/\s+/).filter(Boolean); const index = loadIndex(directory);
  return index.entries.filter((entry) => terms.every((term) => `${entry.summary} ${entry.tags.join(" ")}`.toLowerCase().includes(term)));
}

export function renderMemory(directory: string): string {
  const index = loadIndex(directory); const sections = MEMORY_FILES.map((file) => readFileSync(join(memoryRoot(directory), file), "utf8").trim()).filter((content) => content.split("\n").length > 1);
  const entries = index.entries.map((entry) => `- [${entry.id}] ${entry.summary}${entry.tags.length ? ` (${entry.tags.join(", ")})` : ""}`);
  return ["# Project Memory Bridge", ...sections, "## Recorded memories", ...(entries.length ? entries : ["- No recorded memories."])].join("\n\n");
}

export function syncAntigravity(directory: string): string {
  ensureStore(directory); const target = join(directory, ".gemini", "memory-bridge.md"); mkdirSync(join(directory, ".gemini"), { recursive: true });
  writeFileSync(target, `${renderMemory(directory)}\n\n<!-- Generated by memory-bridge. Edit .memory/, then run memory-bridge sync --to antigravity. -->\n`, "utf8"); return relative(directory, target);
}

export function syncOpencode(directory: string): string {
  ensureStore(directory); const target = join(directory, ".opencode", "memory-bridge.md"); mkdirSync(join(directory, ".opencode"), { recursive: true });
  writeFileSync(target, `${renderMemory(directory)}\n\n<!-- Generated by memory-bridge. Edit .memory/, then run memory-bridge sync --to opencode. -->\n`, "utf8"); return relative(directory, target);
}

export const MemoryBridgePlugin: Plugin = async ({ directory }) => {
  const injectedSessions = new Set<string>();
  return {
  tool: {
    remember: tool({ description: "Persist explicit project memory in versioned .memory/. Never use for secrets.", args: { text: tool.schema.string(), tags: tool.schema.array(tool.schema.string()).optional() }, async execute(args, context) { const entry = addMemory(context.directory, args.text, args.tags ?? [], "opencode"); return `Memory recorded: ${entry.id}`; } }),
    memory_search: tool({ description: "Search versioned project memory by text and tag.", args: { query: tool.schema.string() }, async execute(args, context) { const entries = searchMemory(context.directory, args.query); return entries.length ? entries.map((entry) => `${entry.id} | ${entry.tags.join(", ") || "untagged"} | ${entry.summary}`).join("\n") : "No matching memory."; } }),
  },
  "chat.message": async (input, output) => {
    // First user message carries readable project memory into session context.
    if (injectedSessions.has(input.sessionID)) return;
    injectedSessions.add(input.sessionID);
    const memory = renderMemory(directory);
    output.parts.push({ id: "", sessionID: input.sessionID, messageID: input.messageID ?? "", type: "text", text: `\n\n${memory}` });
  },
  };
};

export default MemoryBridgePlugin;
